TOPICS = [
    "Datenschutz",
    "IT-Sicherheit",
    "Arbeitsschutz",
    "Brandschutz",
    "Erste Hilfe",
    "Compliance",
    "Onboarding",
    "Führung",
    "Kommunikation",
    "Projektmanagement",
    "Zeitmanagement",
    "Microsoft 365",
    "Informationssicherheit",
    "Cybersecurity",
    "DSGVO",
    "Remote Work",
    "Präsentationstechniken",
    "Konfliktmanagement",
    "Nachhaltigkeit",
    "Qualitätsmanagement",
    "Versicherungsgrundlagen",
    "Schadenbearbeitung",
    "Kundenberatung",
    "Vertrieb im Innendienst"
]